#!/bin/bash
echo "Setting up the dependencies..."
echo "Setting up pip for the correct version of python..."
python get-pip.py
echo "Installing nltk"
pip install --user nltk
echo "Installing numpy ..."
pip install --user numpy
echo "Getting required nltk packages..."
python -m nltk.downloader punkt
python -m nltk.downloader averaged_perceptron_tagger
echo "Running generator1.py ..." 
python generator1.py $1
echo "Building liblinear-1.93 toolkit..."
cd liblinear-1.93
make
echo "Predicting the incident types of the documents in the file" $1 "..."
./predict ../docWordVecs_tst.txt SVMPrimerClassifier ../predIncidents.txt > acc.txt
cd ../
echo "Running generator2_multi.py ..." 
python generator2_multi.py
cd liblinear-1.93
echo "Predicting WEAPON, TARGET, VICTIM, PERP INDIV and PERP ORG BIO tags in the documents of the file" $1 "..."
./predict ../BIO_vectors_tst.txt multi_SVMPrimerClassifier ../predBIOs.txt > acc.txt

cd ../
echo "Running generator3_multi.py ..." 
python generator3_multi.py $1
